services:
  products.api:
    image: ${DOCKER_REGISTRY-}spacelaunches
    container_name: spacelaunches.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  products.database:
    image: postgres:latest
    container_name: spacelaunches.database
    environment:
      - POSTGRES_DB=spacelaunches
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    volumes:
      - ./.containers/products-db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - app-network

  products.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge